/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SwingUI;
import java.io.InputStreamReader;
import java.net.IDN;
import edu.neu.csye6200.*;
import java.awt.EventQueue;
//import jdk.internal.agent.resources.agent;
import java.lang.Object.*;
import javax.swing.JOptionPane;

/**
 *
 * @author JiayingXie
 */
public class HireTeacherUI extends javax.swing.JFrame {
    
//    // this helper method could be called in other class, but will use thread
//	public static void initializeLoginView() {
//		EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				try {
//					HireTeacherUI window = new HireTeacherUI();
//                                        window.setVisible(true);
//				} catch (Exception e) {
//					e.printStackTrace();
//				}
//			}
//		});
//	}    
    
    /** Creates new form HireTeacherUI */
    public HireTeacherUI() {
        initComponents();
        // width and height of the frame
        setSize(800, 500);
        // display centered
        setLocationRelativeTo(null);         
    }
    
    // ??? string builder?
//    String newTeacherInformation;
    String defaultPassward = "000000";

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTeacherId = new javax.swing.JLabel();
        jLabelTeacherFirstName = new javax.swing.JLabel();
        jLabelTeacherLastName = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelTeacherHireDate = new javax.swing.JLabel();
        jTextid = new javax.swing.JTextField();
        jTextFieldFIrstName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldHiredate = new javax.swing.JTextField();
        jButtonHireTeacher = new javax.swing.JButton();
        jButtonBackToPreviousPage = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hire teacher");

        jLabelTeacherId.setText("TeacherId");

        jLabelTeacherFirstName.setText("Teacher first name");

        jLabelTeacherLastName.setText("Teacher last name");

        jLabelAge.setText("Teacher age");

        jLabelTeacherHireDate.setText("Teacher hire date");

        jTextid.setColumns(15);
        jTextid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextid.setMaximumSize(new java.awt.Dimension(15, 21));
        jTextid.setPreferredSize(new java.awt.Dimension(15, 21));

        jTextFieldFIrstName.setColumns(15);

        jButtonHireTeacher.setText("Hire teacher");
        jButtonHireTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHireTeacherActionPerformed(evt);
            }
        });

        jButtonBackToPreviousPage.setText("Back");
        jButtonBackToPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToPreviousPageActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Log out");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBackToPreviousPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogout))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHireTeacher))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTeacherLastName)
                            .addComponent(jLabelTeacherId)
                            .addComponent(jLabelAge)
                            .addComponent(jLabelTeacherHireDate)
                            .addComponent(jLabelTeacherFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAge, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFIrstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldHiredate))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonBackToPreviousPage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTeacherId)
                    .addComponent(jTextid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTeacherFirstName)
                    .addComponent(jTextFieldFIrstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTeacherLastName)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAge)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTeacherHireDate)
                    .addComponent(jTextFieldHiredate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHireTeacher)
                    .addComponent(jButtonReset))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHireTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHireTeacherActionPerformed
        // TODO add your handling code here:
    	String s = jTextid.getText() + "," + jTextFieldFIrstName.getText() + "," + jTextFieldLastName.getText() + "," + 
                jTextFieldAge.getText() + "," + this.defaultPassward + "," + jTextFieldHiredate.getText();
        ManagerFactory managerfactory = new ManagerFactory();
        managerfactory.getObject().hireTeacher(s);
        Object[] options = { "OK" };
        JOptionPane.showOptionDialog(null, "Click OK to continue", "Hire teacher successfully!.",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);        
    }//GEN-LAST:event_jButtonHireTeacherActionPerformed

    private void jButtonBackToPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToPreviousPageActionPerformed
        // TODO add your handling code here:
        new ManagerUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackToPreviousPageActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        new WelcomeUI();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextid.setText("");
        jTextFieldFIrstName.setText("");
        jTextFieldLastName.setText("");
        jTextFieldAge.setText("");
        jTextFieldHiredate.setText("");        
    }//GEN-LAST:event_jButtonResetActionPerformed

    
//    int i = 0;
//    private String myNewString(String s){
//        String result = s + ",";
//        return result;
//    }
//    String tempString = myNewString(s);

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HireTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HireTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HireTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HireTeacherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HireTeacherUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToPreviousPage;
    private javax.swing.JButton jButtonHireTeacher;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelTeacherFirstName;
    private javax.swing.JLabel jLabelTeacherHireDate;
    private javax.swing.JLabel jLabelTeacherId;
    private javax.swing.JLabel jLabelTeacherLastName;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldFIrstName;
    private javax.swing.JTextField jTextFieldHiredate;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextid;
    // End of variables declaration//GEN-END:variables

}
