/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SwingUI;

import edu.neu.csye6200.*;
import java.awt.EventQueue;
import java.util.List;

/**
 *
 * @author JiayingXie
 */
public class ManagerUI extends javax.swing.JFrame {
//    // this helper method could be called in other class, but will use thread
//	public static void initializeLoginView() {
//		EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				try {
//					ManagerUI window = new ManagerUI();
//                                        window.setVisible(true);
//				} catch (Exception e) {
//					e.printStackTrace();
//				}
//			}
//		});
//	}
    /**
     * Creates new form ManagerUI
     */
    public ManagerUI() {
        initComponents();
        // width and height of the frame
        setSize(800, 500);
        // display centered
        setLocationRelativeTo(null);          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonHireTeacher = new javax.swing.JButton();
        jButtonEnrollStudent = new javax.swing.JButton();
        jButtonShowAllTeachers = new javax.swing.JButton();
        jButtonShowAllStudents = new javax.swing.JButton();
        jButtonBackToPreviousPage = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager page");

        jButtonHireTeacher.setText("Hire teacher");
        jButtonHireTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHireTeacherActionPerformed(evt);
            }
        });

        jButtonEnrollStudent.setText("Enroll student");
        jButtonEnrollStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnrollStudentActionPerformed(evt);
            }
        });

        jButtonShowAllTeachers.setText("Teacher list");
        jButtonShowAllTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllTeachersActionPerformed(evt);
            }
        });

        jButtonShowAllStudents.setText("Student list");
        jButtonShowAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllStudentsActionPerformed(evt);
            }
        });

        jButtonBackToPreviousPage.setText("Back");
        jButtonBackToPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackToPreviousPageActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Log out");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBackToPreviousPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonShowAllTeachers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonShowAllStudents))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonHireTeacher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1424, Short.MAX_VALUE)
                        .addComponent(jButtonEnrollStudent)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonBackToPreviousPage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHireTeacher)
                    .addComponent(jButtonEnrollStudent))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShowAllTeachers)
                    .addComponent(jButtonShowAllStudents))
                .addContainerGap(1094, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHireTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHireTeacherActionPerformed
        // TODO add your handling code here:
        // ????
//        HireTeacherUI hireTeacherPage = new HireTeacherUI();
//        HireTeacherUI.initializeLoginView();
        new HireTeacherUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonHireTeacherActionPerformed

    private void jButtonBackToPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackToPreviousPageActionPerformed
        // TODO add your handling code here:
        new MyLoginGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackToPreviousPageActionPerformed

    private void jButtonEnrollStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnrollStudentActionPerformed
        // TODO add your handling code here:
        new EnrollStudentUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEnrollStudentActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        new WelcomeUI();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonShowAllTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllTeachersActionPerformed
        // TODO add your handling code here:
        new TeacherListUI().setVisible(true);
//        new SecondTeacherListUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonShowAllTeachersActionPerformed

    private void jButtonShowAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllStudentsActionPerformed
        // TODO add your handling code here:
//    StudentListFactory studentListFactory = new StudentListFactory();
//    List<Student> studentList = studentListFactory.getObject().generateAndGetList();
//    int cnt = studentList.size();
//    System.out.println(cnt);
//    Object[][] tableValues = new Object[cnt][9];
//    for(int i = 0; i < cnt; ++i){
//        tableValues[i][0] = studentList.get(i).getStuId();
//        tableValues[i][1] = studentList.get(i).getAge();
//        tableValues[i][2] = studentList.get(i).getFirstName();
//        tableValues[i][3] = studentList.get(i).getLastName();
//        tableValues[i][4] = studentList.get(i).getParentFirstName();
//        tableValues[i][5] = studentList.get(i).getParentLastName();
//        tableValues[i][6] = studentList.get(i).getAddress();
//        tableValues[i][7] = studentList.get(i).getParentPhone();
//    }
        new StudentListUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonShowAllStudentsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManagerUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackToPreviousPage;
    private javax.swing.JButton jButtonEnrollStudent;
    private javax.swing.JButton jButtonHireTeacher;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonShowAllStudents;
    private javax.swing.JButton jButtonShowAllTeachers;
    // End of variables declaration//GEN-END:variables
}
